# Generated by Django 4.1.3 on 2023-12-04 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('parent', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('completed', models.BooleanField()),
                ('archived', models.BooleanField()),
                ('lastActivity', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='user_roles',
            fields=[
                ('userid', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.TextField(max_length=32)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('task', models.TextField()),
                ('order', models.IntegerField(unique=True)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.status'),
        ),
        migrations.AddField(
            model_name='projects',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.type'),
        ),
        migrations.CreateModel(
            name='notes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
        ),
        migrations.CreateModel(
            name='links',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=64)),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
        ),
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('doc', models.BinaryField()),
                ('ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.projects')),
            ],
        ),
    ]
