# Generated by Django 4.1.3 on 2023-12-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_document_link_note_project_task_user_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lastActivity',
            field=models.DateTimeField(),
        ),
    ]
